PUT http://localhost:3002/api/user/634a5bdb441c0826a1b5e678
Content-Type: application/json

{
    "email": "camarabubacarr@gm",
    "firstname": "Shiddiqq",
    "minit": "",
    "lastname": "Camara",
    "role": "Admin"
}